AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        GEOCODING_API_URL: https://geocoding-api.open-meteo.com/v1/search
        WEATHER_API_URL: https://api.open-meteo.com/v1/forecast

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambdas/helloHandler.handler
      Runtime: nodejs22.x
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/lambdas/helloHandler.ts

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambdas/healthHandler.handler
      Runtime: nodejs22.x
      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/lambdas/healthHandler.ts

  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambdas/weatherHandler.handler
      Runtime: nodejs22.x
      Timeout: 15
      Events:
        WeatherApi:
          Type: Api
          Properties:
            Path: /weather/{city}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/lambdas/weatherHandler.ts

  ForecastFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambdas/forecastHandler.handler
      Runtime: nodejs22.x
      Timeout: 15
      Events:
        WeatherApi:
          Type: Api
          Properties:
            Path: /forecast/{city}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/lambdas/forecastHandler.ts
