name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: eu-north-1
      SAM_CLI_TELEMETRY: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install esbuild globally
        run: npm install -g esbuild

      - name: Run typecheck
        run: npm run typecheck

      - name: Run tests
        run: npm test

      # 1. install AWS SAM CLI on GitHub
      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true # install the official package

      # 2. check template.yaml
      - name: Validate SAM template
        run: sam validate

      # 3. build Lambda functions
      - name: Build SAM application
        run: sam build
